[project]
name = "litigpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jsonlines>=4.0.0",
    "mlflow>=3.3.2",
    "pandas>=2.3.2",
    "pyarrow>=21.0.0",
    "torch>=2.8.0",
    "transformers>=4.56.1",
    "zstandard>=0.24.0",
    "zstd>=1.5.7.3",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
